typography_spectrum: 0.5704077081754804
content_rating:
  adult: false
color:
  brandStrength: 0.5662612065207213
  lightness: 0.7104604772757739
  saturation: 0.5551977457944304
  rhythmicContrast: 0.2899036086164415
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.6586022966075689
author:
  email: adrian.dahlin@gmail.com
  name: Adrian Dahlin
name: Adrian Dahlin
navigation:
  - name: School
    url: cusp.nyu.edu
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29d3f7b9-91d8-4f0a-a1c0-de1e21af0086.jpg
title: Conversatin'
description: 'Brother, citizen, founder, musicmaker.'
